global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets: ['api:3000']

  - job_name: worker
    metrics_path: /metrics
    static_configs:
      - targets: ['worker:9464']

  - job_name: rabbitmq
    metrics_path: /metrics
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: rabbitmq-queues
    metrics_path: /metrics/per-object
    static_configs:
      - targets: ['rabbitmq:15692']
